version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    command: --serviceExecutor adaptive
    volumes:
      - ./database/data:/data/db
    restart: always

  server:
    build: ./server
    container_name: server
    image: server
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  ui:
    build: ./ui
    container_name: ui
    image: ui
    ports:
      - "4200:4200"
